service: stunning-journey
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region,'us-east-1'}
  memory: 128
  tags:
    customer: wazuh
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}

plugins:
  - serverless-wsgi
  - serverless-layers

package:
  patterns:
    - "!venv/**"
    - "!node_modules/**"
    - "!__pycache__/**"
    - "!__test__/**"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

custom:
  wsgi:
    app: src/app.app
    packRequirements: false
